function erro(erro1){
    throw('erro de execu√ßao')
}